# -*- coding: utf-8 -*-
"""Caluclator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P8xa_1trz78Mw809EM2jdQ_xGu3hKFyI
"""

def calculator():
    print("Welcome to the calculator!")

num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

operation = input("Enter the operation (+, -, *, /): ")

if operation == "+":
        result = num1 + num2
        print(f"{num1} + {num2} = {result}")

if operation == "-":
        result = num1 - num2
        print(f"{num1} - {num2} = {result}")

if operation == "*":
        result = num1 * num2
        print(f"{num1} * {num2} = {result}")

if operation == "/":
        if num2 != 0:
            result = num1 / num2
            print(f"{num1} / {num2} = {result}")
        else:
            print("Error: Division by zero is not allowed.")

print("Error: Invalid operation.")

again = input("Do you want to perform another calculation? (y/n): ")
if again.lower() == "y":
        calculator()

calculator()

def calculator():
    print("Welcome to the calculator!")

    while True:
        try:
            num1 = float(input("Enter the first number: "))
            num2 = float(input("Enter the second number: "))
            break
        except ValueError:
            print("Invalid input. Please enter a number.")

    while True:
        operation = input("Enter the operation (+, -, *, /): ")
        if operation in ["+", "-", "*", "/"]:
            break
        else:
            print("Error: Invalid operation.")

    if operation == "+":
        result = num1 + num2
        print(f"{num1} + {num2} = {result}")
    elif operation == "-":
        result = num1 - num2
        print(f"{num1} - {num2} = {result}")
    elif operation == "*":
        result = num1 * num2
        print(f"{num1} * {num2} = {result}")
    elif operation == "/":
        if num2 != 0:
            result = num1 / num2
            print(f"{num1} / {num2} = {result}")
        else:
            print("Error: Division by zero is not allowed.")

    again = input("Do you want to perform another calculation? (y/n): ")
    if again.lower() == "y":
        calculator()

calculator()