# -*- coding: utf-8 -*-
"""DO-TO LIST

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uc3adUi0B0f4odQGWBDjj92skWfRd73F

A To-Do List application is a useful project that helps users manage
and organize their tasks efficiently. This project aims to create a
command-line or GUI-based application using Python, allowing
users to create, update, and track their to-do lists
"""

# Define a list to store the tasks
tasks = []

def show_menu():
    print("To-Do List Application")
    print("1. Add Task")
    print("2. View Tasks")
    print("3. Mark Task as Complete")
    print("4. Remove Task")
    print("5. Exit")

def add_task():
    task = input("Enter the task: ")
    tasks.append(task)
    print("Task added successfully!")

def view_tasks():
    if not tasks:
        print("No tasks found.")
    else:
        print("Tasks:")
        for index, task in enumerate(tasks, start=1):
            print(f"{index}. {task}")

def mark_complete():
    view_tasks()
    task_index = int(input("Enter the task number to mark as complete: "))
    if 1 <= task_index <= len(tasks):
        completed_task = tasks.pop(task_index - 1)
        print(f"Task '{completed_task}' marked as complete.")
    else:
        print("Invalid task number.")

def remove_task():
    view_tasks()
    task_index = int(input("Enter the task number to remove: "))
    if 1 <= task_index <= len(tasks):
        removed_task = tasks.pop(task_index - 1)
        print(f"Task '{removed_task}' removed successfully.")
    else:
        print("Invalid task number.")

while True:
    show_menu()
    choice = input("Enter your choice (1-5): ")

    if choice == "1":
        add_task()
    elif choice == "2":
        view_tasks()
    elif choice == "3":
        mark_complete()
    elif choice == "4":
        remove_task()
    elif choice == "5":
        print("Exiting the application...")
        break
    else:
        print("Invalid choice. Please try again.")